version: '3'

services:
  proxy:
    restart: always
    container_name: eth_rooms_proxy
    image: rafpe/docker-haproxy-rsyslog
    volumes:
      - ./proxy/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8080:80
    links:
      - eth_rooms_api
      - eth_rooms_client

  api:
    container_name: eth_rooms_api
    image: benarmstrong/eth_rooms_api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    links:
      - database
    depends_on:
      - database
    env_file:
      - ./api/.env

  client:
    container_name: eth_rooms_client
    image: benarmstrong/eth_rooms_client
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile

  database:
    container_name: eth_rooms_database
    image: benarmstrong/eth_rooms_db:latest
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        - 'dbname=eth_rooms'
        - 'db_password=postgres'
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
